#운영에 대한 공통 설정 - 각 개별환경에 맞는 properties 설정 (데이터베이스, 외부 설정정보 등)
user:
  email: "soon@test.com"
  nickname: "soon"
  age: 200
  auth: false
  amount: 101

spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
#    data: classpath:init.sql # 시작될 때 실행시킬 script

logging:
  level:
    ROOT: info